version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    working_directory: ~/book
    branches:
      only: deploy_book
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "78:a1:d7:f3:b5:f3:7f:04:c1:5f:91:d8:6f:a0:9f:84"
      - deploy:
          name: deploy to product
          command: |
            if [ "${CIRCLE_BRANCH}" == "deploy_book"  ]; then
              scp -oStrictHostKeyChecking=no -r [!.]* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}
            fi
